const actionTypes = {
    FAILURE: 'FAILURE',
    LOAD_DATA: 'LOAD_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_MORE : 'LOAD_MORE',
    LOAD_MORE_SUCCESS: 'LOAD_MORE_SUCCESS',
    LOADING: 'LOADING'
  };

  export {
    actionTypes
  };